// THE BASIS. The standard library, written in the language it is for.
//
// Part of src/lang/. Moved out of src/game/ai_ml.js at v1.288 (M3).
//
// This file exports the SOURCE only. Loading it is the interpreter's job
// (interp.js), because loading means running, and a library that imported the
// evaluator to define itself would be a cycle. Keeping it as text also keeps
// the standing rule true: it is written in the language, not underneath it, and
// a player can read the same `map` they would have written.

// THE LIBRARY, written in the language it is for.
//
// It is loaded as source rather than built as JavaScript builtins, so `List.map`
// is the same map a player would write and can be read with the same eyes. The
// structures are the ones the manuals name, minus everything this build has no
// way to do.
export const PRELUDE = [
  "datatype 'a option = NONE | SOME of 'a",
  'datatype order = LESS | EQUAL | GREATER',
  '',
  '(* Composition and sequencing. Standard ML has these infix in the top-level',
  '   environment, so the fixity is declared here rather than seeded into the',
  '   parser: fixity is a fact about a program, and a program that wants `o`',
  '   for something else can say `nonfix o` and have it. *)',
  'fun o (f, g) = fn x => f (g x)',
  'infixr 3 o',
  'fun before (a, b) = a',
  'infix 0 before',
  'fun ignore _ = ()',
  '',
  '(* THE STANDARD EXCEPTIONS. The Basis raises these by name, and until v1.301',
  '   the primitives threw a message instead, so `hd nil handle Empty => 0` had',
  '   nothing to catch. They are declared here, in the language, so `handle`',
  '   sees ordinary constructors and nothing special had to be taught to it. *)',
  'exception Empty',
  'exception Div',
  'exception Subscript',
  'exception Match',
  'exception Fail',
  '(* print is Basis: it writes a string out and answers unit. *)',
  'fun print s = echo s',
  '',
  'structure List = struct',
  '  fun null nil = true | null _ = false',
  '  fun length nil = 0 | length (_ :: t) = 1 + length t',
  '  fun map f nil = nil | map f (h :: t) = f h :: map f t',
  '  fun filter p nil = nil',
  '    | filter p (h :: t) = if p h then h :: filter p t else filter p t',
  '  fun foldl f b nil = b | foldl f b (h :: t) = foldl f (f h b) t',
  '  fun foldr f b nil = b | foldr f b (h :: t) = f h (foldr f b t)',
  '  fun rev l = foldl (fn h => fn a => h :: a) nil l',
  '  fun exists p nil = false | exists p (h :: t) = p h orelse exists p t',
  '  fun all p nil = true | all p (h :: t) = p h andalso all p t',
  '  fun find p nil = NONE',
  '    | find p (h :: t) = if p h then SOME h else find p t',
  '  fun app f nil = () | app f (h :: t) = (f h; app f t)',
  '  fun last (h :: nil) = h | last (h :: t) = last t',
  '  fun nth (h :: t, n) = if n = 0 then h else nth (t, n - 1)',
  '  fun take (l, n) = if n = 0 then nil else hd l :: take (tl l, n - 1)',
  '  fun drop (l, n) = if n = 0 then l else drop (tl l, n - 1)',
  '  fun concat nil = nil | concat (h :: t) = h @ concat t',
  '  fun tabulate (n, f) = if n = 0 then nil else tabulate (n - 1, f) @ [f (n - 1)]',
  '  (* partition returns the pair (kept, rejected), in the original order. *)',
  '  fun partition p nil = (nil, nil)',
  '    | partition p (h :: t) =',
  '        let val (y, n) = partition p t',
  '        in if p h then (h :: y, n) else (y, h :: n) end',
  '  (* zip stops at the shorter list, as ListPair.zip does. *)',
  '  fun zip (nil, _) = nil',
  '    | zip (_, nil) = nil',
  '    | zip (a :: as1, b :: bs) = (a, b) :: zip (as1, bs)',
  '  fun unzip nil = (nil, nil)',
  '    | unzip ((a, b) :: t) = let val (x, y) = unzip t in (a :: x, b :: y) end',
  'end',
  '',
  'structure ListPair = struct',
  '  val zip = List.zip',
  '  val unzip = List.unzip',
  'end',
  '',
  'structure Char = struct',
  '  fun isDigit c = ord c >= 48 andalso ord c <= 57',
  '  fun isUpper c = ord c >= 65 andalso ord c <= 90',
  '  fun isLower c = ord c >= 97 andalso ord c <= 122',
  '  fun isAlpha c = isUpper c orelse isLower c',
  '  fun isAlphaNum c = isAlpha c orelse isDigit c',
  '  fun isSpace c = ord c = 32 orelse ord c = 9 orelse ord c = 10',
  '  fun toUpper c = if isLower c then chr (ord c - 32) else c',
  '  fun toLower c = if isUpper c then chr (ord c + 32) else c',
  '  fun toString c = makestring c',
  '  fun compare (a, b) = Int.compare (ord a, ord b)',
  'end',
  '',
  'structure String = struct',
  '  fun size s = length (explode s)',
  '  fun sub (s, n) = List.nth (explode s, n)',
  '  fun map f s = implode (List.map f (explode s))',
  '  fun rev s = implode (List.rev (explode s))',
  '  fun concat nil = "" | concat (h :: t) = h ^ concat t',
  '  fun isPrefix (p, s) = List.take (explode s, size p) = explode p',
  '  fun substring (s, i, n) = implode (List.take (List.drop (explode s, i), n))',
  '  fun extract (s, i, NONE) = implode (List.drop (explode s, i))',
  '    | extract (s, i, SOME n) = substring (s, i, n)',
  '  (* translate maps each character to a STRING and joins the results, which',
  '     is what lets it delete and expand as well as replace. *)',
  '  fun translate f s = concat (List.map f (explode s))',
  '  fun concatWith sep nil = ""',
  '    | concatWith sep (h :: nil) = h',
  '    | concatWith sep (h :: t) = h ^ sep ^ concatWith sep t',
  '  (* tokens splits on every character the predicate accepts and DROPS empty',
  '     fields; fields keeps them. That is the only difference between them. *)',
  '  fun fields p s =',
  '        let fun go (nil, cur) = [implode (List.rev cur)]',
  '              | go (c :: t, cur) =',
  '                  if p c then implode (List.rev cur) :: go (t, nil)',
  '                  else go (t, c :: cur)',
  '        in go (explode s, nil) end',
  '  fun tokens p s = List.filter (fn f => f <> "") (fields p s)',
  '  fun toString s = s',
  '  val explode = explode',
  '  val implode = implode',
  '  (* compare walks the two strings together and answers at the first',
  '     character that differs; a prefix is LESS than what extends it. *)',
  '  fun compare (a, b) =',
  '        let fun go (nil, nil) = EQUAL',
  '              | go (nil, _) = LESS',
  '              | go (_, nil) = GREATER',
  '              | go (x :: xs, y :: ys) =',
  '                  case Char.compare (x, y) of',
  '                    EQUAL => go (xs, ys)',
  '                  | r => r',
  '        in go (explode a, explode b) end',
  'end',
  '',
  'structure Int = struct',
  '  fun abs n = if n < 0 then 0 - n else n',
  '  fun min (a, b) = if a < b then a else b',
  '  fun max (a, b) = if a > b then a else b',
  '  fun toString n = makestring n',
  '  fun compare (a, b) = if a < b then LESS else if a > b then GREATER else EQUAL',
  '  fun sign n = if n < 0 then ~1 else if n > 0 then 1 else 0',
  '  (* fromString answers an option: a string that is not a numeral is not an',
  '     error, it is simply NONE, and the caller decides what that means. *)',
  '  fun fromString s =',
  '        let fun digits (nil, acc, seen) = if seen then SOME acc else NONE',
  '              | digits (c :: t, acc, seen) =',
  '                  if Char.isDigit c then digits (t, acc * 10 + (ord c - 48), true)',
  '                  else NONE',
  '        in case explode s of',
  '             nil => NONE',
  '           | #"~" :: t => (case digits (t, 0, false) of',
  '                             SOME n => SOME (0 - n)',
  '                           | NONE => NONE)',
  '           | cs => digits (cs, 0, false)',
  '        end',
  'end',
  '',
  'structure Real = struct',
  '  fun abs x = if x < 0.0 then 0.0 - x else x',
  '  fun min (a, b) = if a < b then a else b',
  '  fun max (a, b) = if a > b then a else b',
  '  fun fromInt n = real n',
  '  fun round x = floor (x + 0.5)',
  '  fun toString x = makestring x',
  'end',
  '',
  'structure Bool = struct',
  '  fun toString true = "true" | toString false = "false"',
  '  fun fromString "true" = SOME true',
  '    | fromString "false" = SOME false',
  '    | fromString _ = NONE',
  '  fun not true = false | not false = true',
  'end',
  '',
  '(* Option\'s members are at top level too, as they are in Standard ML. *)',
  'fun valOf (SOME x) = x',
  'fun isSome NONE = false | isSome (SOME _) = true',
  'fun getOpt (NONE, d) = d | getOpt (SOME x, _) = x',
  '',
  'structure Option = struct',
  '  fun isSome NONE = false | isSome (SOME _) = true',
  '  fun valOf (SOME x) = x',
  '  fun getOpt (NONE, d) = d | getOpt (SOME x, _) = x',
  '  fun map f NONE = NONE | map f (SOME x) = SOME (f x)',
  '  fun join NONE = NONE | join (SOME x) = x',
  '  fun filter p x = if p x then SOME x else NONE',
  'end',
].join('\n');
